server:
  port: 8000
spring:
  application:
    name: gateway-server
  config:
    import: classpath:/bootstrap.yml
  cloud:
    gateway:
      routes:
        - id: devpath-community-server
          uri: lb://DEVPATH-COMMUNITY-SERVER
          predicates:
            - Path=/api/community-server/**
          filters:
            - RewritePath=/api/community-server/(?<segment>.*), /$\{segment}
            - RemoveRequestHeader=Content-Length
        - id: devpath-feature-server
          uri: lb://DEVPATH-FEATURE-SERVER
          predicates:
            - Path=/api/feature-server/**
          filters:
            - RewritePath=/api/feature-server/(?<segment>.*), /$\{segment}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka